---
all:
  children:
    initial_controller:
      hosts:
        k0s-1:
    controller:
      hosts:
        k0s-2:
        k0s-3:
    worker:
      hosts:
        k0s-4:
        k0s-5:
        k0s-6:
        k0s-7:
  hosts:
    k0s-1:
      ansible_host: 192.168.122.31
    k0s-2:
      ansible_host: 192.168.122.32
    k0s-3:
      ansible_host: 192.168.122.56
    k0s-4:
      ansible_host: 192.168.122.57
    k0s-5:
      ansible_host: 192.168.122.58
    k0s-6:
      ansible_host: 192.168.122.60
    k0s-7:
      ansible_host: 192.168.122.61
  vars:
    ansible_user: k0s
